---

- name: "User | Debian | Remove | Removing user '{{ name }}'"
  ansible.builtin.user:
    name: "{{ name }}"
    state: absent
    remove: "{{ user.remove }}"
    force: "{{ user.force_remove }}"

- name: "User | Debian | Remove | Removing ssh authorized-keys for user '{{ name }}'"
  ansible.builtin.file:
    state: absent
    path: "{{ user.sshpub_path | replace(SYS_AUTH_HC.sshpub_user_var, name) }}"
  when:
    - user.sshpub_path is defined
    - "user.sshpub_path not in ['', none, ' ']"

- name: "User | Debian | Remove | Removing privileges for user '{{ name }}'"
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ user.sudoers_file_prefix }}_{{ name | safe_key }}"
    state: absent

- name: "User | Debian | Remove | Removing primary group for user '{{ name }}'"
  ansible.builtin.include_tasks: group_rm.yml
  vars:
    group_name: "{{ user.group | default(name) }}"
  no_log: true
  when: user.group|default(name) not in SYS_AUTH.groups
