---

- name: "User | Debian | Remove | Removing user '{{ user.key }}'"
  ansible.builtin.user:
    name: "{{ user.key }}"
    state: 'absent'
    remove: "{{ user.value.remove | default(default_user_config.remove) }}"
    force: "{{ user.value.force_remove | default(default_user_config.force_remove) }}"

- name: "User | Debian | Remove | Removing ssh authorized-keys for user '{{ user.key }}' in custom path"
  ansible.builtin.file:
    state: absent
    path: "{{ user_sshpub_path | replace(user_sshpub_path_name_var, user.key) }}"
  when:
    - user_sshpub_path is defined
    - user_sshpub_path != ''

- name: "User | Debian | Remove | Removing privileges for user '{{ user.key }}'"
  file:
    path: "/etc/sudoers.d/{{ user.value.sudoers_file_prefix | default(default_user_config.sudoers_file_prefix) }}_{{ user.key }}"
    state: absent

- name: "User | Debian | Remove | Removing primary group for user '{{ user.key }}'"
  include_tasks: debian/group_rm.yml
  args:
    apply:
      vars:
        group:
          key: "{{ user.value.group | default(user.key) }}"
  when: user.value.group|default(user.key) not in user_groups
