---

- name: User | Debian | Setting distro-vars
  ansible.builtin.set_fact:
    password_disabled: '!'

- name: User | Debian | Adding users
  ansible.builtin.include_tasks: user_add.yml
  vars:
    user: "{{ defaults_user | combine(user_item.value, recursive=true) }}"
    name: "{{ user_item.key }}"
  loop_control:
    loop_var: user_item
  with_dict: "{{ SYS_AUTH.users }}"
  no_log: true  # an error here will most probably mean that you forgot to supply a vault-secret via '--ask-vault-pass'
  when: >
    user.state == 'present' and
    (user.scope is undefined or
    inventory_hostname in user.scope|ensure_list or
    user.scope|ensure_list|intersection(groups))
  # user should be created
  # user is in host-scope

- name: User | Debian | Removing users
  ansible.builtin.include_tasks: user_rm.yml
  vars:
    user: "{{ defaults_user | combine(user_item.value, recursive=true) }}"
    name: "{{ user_item.key }}"
  loop_control:
    loop_var: user_item
  with_dict: "{{ SYS_AUTH.users }}"
  no_log: true
  when: >
    user.state != 'present' or
    (user.scope is defined and
    inventory_hostname not in user.scope|ensure_list and
    not user.scope|ensure_list|intersection(groups))
