---

- name: User | Debian | Setting distro-vars
  ansible.builtin.set_fact:
    password_disabled: '!'

- name: User | Debian | Adding users
  ansible.builtin.include_tasks: user_add.yml
  loop_control:
    loop_var: user
  with_dict: "{{ users }}"
  no_log: true  # an error here will most probably mean that you forgot to supply a vault-secret via '--ask-vault-pass'
  when: >
    (user.value.absent is undefined or not user.value.absent) and
    ((user.value.present is defined and user.value.present) or 
    (user.value.state|default(default_user_config.state) == 'present')) and
    (user.value.scope is undefined or
    inventory_hostname in user.value.scope|ensure_list or
    user.value.scope|ensure_list|intersection(groups))
  # user should be created
  # user is in host-scope

- name: User | Debian | Removing users
  ansible.builtin.include_tasks: user_rm.yml
  loop_control:
    loop_var: user
  with_dict: "{{ users }}"
  no_log: true
  when: >
    (user.value.present is undefined or not user.value.present) and
    ((user.value.absent is defined and user.value.absent) or
    (user.value.state|default(default_user_config.state) != 'present')) or
    (user.value.scope is defined and 
    inventory_hostname not in user.value.scope|ensure_list and
    not user.value.scope|ensure_list|intersection(groups))
